# Generated by Django 6.1 on 2026-09-01 11:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostFilme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=250)),
                ("slug", models.SlugField(max_length=250)),
                ("comentario", models.TextField()),
                ("nota", models.IntegerField()),
                (
                    "publicado_em",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-publicado_em"],
                "indexes": [
                    models.Index(
                        fields=["-publicado_em"], name="filmes_post_publica_6fbbd2_idx"
                    )
                ],
            },
        ),
    ]
