# Generated by Django 6.1 on 2026-09-07 23:59

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_postfilme_tags'),
    ]

    operations = [
        TrigramExtension(),
    ]

