# Generated by Django 6.1 on 2026-09-17 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('capa', models.ImageField(upload_to='filmes/%Y/%m/%d/')),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filmes_adicionados', to=settings.AUTH_USER_MODEL)),
                ('usuarios_curtiram', models.ManyToManyField(blank=True, related_name='filmes_curtidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='catalogo_fi_criado__4e393a_idx')],
            },
        ),
    ]
