# Generated by Django 6.1 on 2026-09-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='url_capa',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
