"""Adicionar cor_avatar

Revision ID: 129b7691c821
Revises: 20f49081633b
Create Date: 2026-06-26 16:46:14.666256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '129b7691c821'
down_revision = '20f49081633b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_fundo', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('cor_icone', sa.String(length=7), nullable=True))
        batch_op.drop_column('cor_avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_avatar', sa.VARCHAR(length=7), nullable=True))
        batch_op.drop_column('cor_icone')
        batch_op.drop_column('cor_fundo')

    # ### end Alembic commands ###
