"""Adicionar cor_avatar

Revision ID: 20f49081633b
Revises: 
Create Date: 2026-06-26 16:40:12.042497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f49081633b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('couples')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_avatar', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cor_avatar')

    op.create_table('couples',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user1_id', sa.INTEGER(), nullable=False),
    sa.Column('user2_id', sa.INTEGER(), nullable=True),
    sa.Column('relationship_date', sa.DATE(), nullable=True),
    sa.Column('relationship_status', sa.VARCHAR(length=30), nullable=False),
    sa.Column('couple_photo', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
