"""add memories domain models

Revision ID: 242f9070d3e7
Revises: 4d5f8bbf4bc5
Create Date: 2026-07-07 08:39:58.147553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242f9070d3e7'
down_revision = '4d5f8bbf4bc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('memory_collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_id', 'slug', name='uq_memory_collection_relationship_slug')
    )
    with op.batch_alter_table('memory_collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_collections_relationship_id'), ['relationship_id'], unique=False)

    op.create_table('memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('memory_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['memory_collections.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memories_collection_id'), ['collection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memories_relationship_id'), ['relationship_id'], unique=False)

    op.create_table('memory_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_photos_memory_id'), ['memory_id'], unique=False)

    op.create_table('memory_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'tag_id', name='uq_memory_tag_memory_tag')
    )
    with op.batch_alter_table('memory_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_tags_memory_id'), ['memory_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_tags_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memory_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_tags_tag_id'))
        batch_op.drop_index(batch_op.f('ix_memory_tags_memory_id'))

    op.drop_table('memory_tags')
    with op.batch_alter_table('memory_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_photos_memory_id'))

    op.drop_table('memory_photos')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memories_relationship_id'))
        batch_op.drop_index(batch_op.f('ix_memories_collection_id'))

    op.drop_table('memories')
    with op.batch_alter_table('memory_collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_collections_relationship_id'))

    op.drop_table('memory_collections')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))

    op.drop_table('tags')
    # ### end Alembic commands ###
