"""add calendar events

Revision ID: 3d63e5a65a1a
Revises: 242f9070d3e7
Create Date: 2026-07-07 09:54:03.854576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d63e5a65a1a'
down_revision = '242f9070d3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.String(length=10), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_relationship_id'), ['relationship_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_relationship_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_event_date'))

    op.drop_table('calendar_events')
    # ### end Alembic commands ###
