"""Adiciona session_version ao usuário

Revision ID: 3f95b355ee77
Revises: d7eb435b6ce5
Create Date: 2026-06-27 19:54:20.553321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f95b355ee77'
down_revision = 'd7eb435b6ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_version', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_version')

    # ### end Alembic commands ###
