"""Criar tabela relationships

Revision ID: 7fc6706e8804
Revises: 3f95b355ee77
Create Date: 2026-07-03 09:18:24.489738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fc6706e8804'
down_revision = '3f95b355ee77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_status', sa.String(length=30), nullable=False),
    sa.Column('relationship_phrase', sa.String(length=255), nullable=True),
    sa.Column('couple_photo', sa.String(length=255), nullable=False),
    sa.Column('relationship_start_date', sa.Date(), nullable=False),
    sa.Column('relationship_end_date', sa.Date(), nullable=True),
    sa.Column('relationship_is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationship_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationship_members')
    op.drop_table('relationships')
    # ### end Alembic commands ###
