"""add piggy bank tables

Revision ID: 8ae4c097f7fc
Revises: 311154046835
Create Date: 2026-07-07 10:31:43.314001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae4c097f7fc'
down_revision = '311154046835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('piggy_banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('piggy_banks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_piggy_banks_relationship_id'), ['relationship_id'], unique=False)

    op.create_table('piggy_bank_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piggy_bank_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['piggy_bank_id'], ['piggy_banks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('piggy_bank_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_piggy_bank_movements_piggy_bank_id'), ['piggy_bank_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_piggy_bank_movements_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('piggy_bank_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piggy_bank_movements_user_id'))
        batch_op.drop_index(batch_op.f('ix_piggy_bank_movements_piggy_bank_id'))

    op.drop_table('piggy_bank_movements')
    with op.batch_alter_table('piggy_banks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piggy_banks_relationship_id'))

    op.drop_table('piggy_banks')
    # ### end Alembic commands ###
