"""Adicionar invitation_code em Relationship

Revision ID: 9b58c83cba55
Revises: 7fc6706e8804
Create Date: 2026-07-06 19:19:35.869855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b58c83cba55'
down_revision = '7fc6706e8804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invitation_code', sa.String(length=12), nullable=True))
        batch_op.create_index(batch_op.f('ix_relationships_invitation_code'), ['invitation_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relationships_invitation_code'))
        batch_op.drop_column('invitation_code')

    # ### end Alembic commands ###
