"""add wishes table

Revision ID: a4faa83824a8
Revises: 8ae4c097f7fc
Create Date: 2026-07-07 10:44:06.486219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4faa83824a8'
down_revision = '8ae4c097f7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('price_estimated', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wishes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wishes_relationship_id'), ['relationship_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishes_relationship_id'))

    op.drop_table('wishes')
    # ### end Alembic commands ###
