"""Descrição da alteração

Revision ID: d7eb435b6ce5
Revises: fb80ce9c8586
Create Date: 2026-06-26 23:23:32.044385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7eb435b6ce5'
down_revision = 'fb80ce9c8586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.DATE(), nullable=True))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
