"""Descrição da alteração

Revision ID: fb80ce9c8586
Revises: f7863161cba0
Create Date: 2026-06-26 23:20:41.705026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb80ce9c8586'
down_revision = 'f7863161cba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.DATE(), nullable=True))
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
